#!/bin/bash
function yes_or_no {
    while true; do
        read -r -p "$* [y/n]: " yn
        case $yn in
            [Yy]*) return 0  ;;
            [Nn]*) echo "Aborted" ; return  1 ;;
        esac
    done
}

docker build -t checkers_db_image .
if docker ps --all | grep -q checkers_db
then
    yes_or_no "Are you sure you want to stop and recreate checkers_db container?" && 
        docker stop checkers_db &&
        docker rm checkers_db
fi
docker run --name checkers_db -dP checkers_db_image 
